version: "3.9"
services:
  contracts:
    container_name: ethdam-contracts
    build:
      context: contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - "./contracts:/app"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    command: mongod

  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
  server_cron:
    build: ./server
    volumes:
      - ./server:/app
    depends_on:
      - contracts
    restart: on-failure

    command: bash -c "npm i && node swap-cron.js"
  autofi-ui:
    build: ./autofi-ui
    volumes:
      - ./autofi:/app
    ports:
      - "5173:5173"
    environment:
      - FACTORY=0xFa64f316e627aD8360de2476aF0dD9250018CFc5

# bs              | [Entrypoint]: 0xFf6974a7732d12499246056f3aCeF80051bB48f5
# ethdam-contracts-jobs              | [Factory]: 0xFa64f316e627aD8360de2476aF0dD9250018CFc5 // 0xFa64f316e627aD8360de2476aF0dD9250018CFc5

# ethdam-contracts-jobs              | [DCAWallet]: 0xBAd3D6f2D86596cE67012A061719E13BaF39772e