version: "3.9"
services:
  contracts:
    container_name: ethdam-contracts
    build:
      context: contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - "./contracts:/app"

  mongo:
    image: mongo:4.2.24
    ports:
      - "27017:27017"
    volumes:
      - /data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    command: mongod

  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
  # autofi-ui:
  #   build: ./autofi
  #   volumes:
  #     - ./autofi:/app
  #   ports:
  #     - 8080:8080
