version: "3.9"
services:
  contracts:
    container_name: ethdam-contracts
    build:
      context: contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - "./contracts:/app"

  contract_jobs:
    container_name: ethdam-contracts-jobs
    depends_on:
      - contracts
    build:
      context: contracts
      dockerfile: Dockerfile
    volumes:
      - "./contracts:/app"
    command: "yarn run hardhat run scripts/deploy-test-context.ts && "

  mongo:
    image: mongo:4.2.24
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    command: mongod

  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
  autofi-ui:
    build: ./autofi-ui
    volumes:
      - ./autofi:/app
    ports:
      - 80:8080
